BEGIN;
DROP TABLE `stat_db_eventathlete`;
DROP TABLE `stat_db_statistic`;
DROP TABLE `stat_db_teamstatistic`;
DROP TABLE `stat_db_athletestatistic`;
DROP TABLE `stat_db_statistictype`;
DROP TABLE `stat_db_statisticcategory`;
DROP TABLE `stat_db_sportposition`;
DROP TABLE `stat_db_scorebreakdown`;
DROP TABLE `stat_db_score`;
ALTER TABLE `stat_db_eventinformation_transportation` DROP FOREIGN KEY `eventinformation_id_refs_id_91f70b9a`;
DROP TABLE `stat_db_eventinformation`;
DROP TABLE `stat_db_eventinformation_transportation`;
DROP TABLE `stat_db_eventparticipant`;
DROP TABLE `stat_db_event`;
DROP TABLE `stat_db_eventtype`;
DROP TABLE `stat_db_eventstatus`;
DROP TABLE `stat_db_transportation`;
ALTER TABLE `stat_db_facility_contact` DROP FOREIGN KEY `facility_id_refs_id_0c8f152a`;
DROP TABLE `stat_db_facility`;
DROP TABLE `stat_db_facility_contact`;
DROP TABLE `stat_db_athlete`;
DROP TABLE `stat_db_student`;
DROP TABLE `stat_db_entitycontact`;
DROP TABLE `stat_db_entity`;
DROP TABLE `stat_db_entitytype`;
DROP TABLE `stat_db_club`;
DROP TABLE `stat_db_sport`;
DROP TABLE `stat_db_level`;
DROP TABLE `stat_db_gender`;
DROP TABLE `stat_db_contactphonenumber`;
DROP TABLE `stat_db_phonenumber`;
DROP TABLE `stat_db_phonetype`;
DROP TABLE `stat_db_emailaddress`;
DROP TABLE `stat_db_emailtype`;
DROP TABLE `stat_db_contactaddress`;
DROP TABLE `stat_db_contact`;
DROP TABLE `stat_db_address`;
DROP TABLE `south_migrationhistory`;

COMMIT;
